version: '3.7'
services:

  farm-faux-cloud:
    image: farm-faux-cloud:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BOUNCE_VERSION=1
